### PR TITLE
Feature Addition: Static members

### PR DESCRIPTION
**Pull request by cjmanca**
Can now specify "static" for functions and properties, to have them be
attached to the class it's self, rather than it's instances. 

Does NOT break backwards compatibility.

Not ready to be merged, but wanted to get things started. Seems to be working correctly, but limited unit tests so far. Would appreciate help thinking of more unit tests.

Two ways to access the inner (private/protected) static scope:

```javascript
var MyClass = JOII.ClassBuilder('MyClass', {}, function (MyClass) { return { 
    'private static number num' : 1,
    'public static string str' : 'Works!',
    'public test()' : function() {
        MyClass.num = 2; // uses the variable passed to this function
        this.getStatic().num = 3; // uses the getStatic() private method to retrieve access to the inner static scope
    }
}});
MyClass.getStr(); // returns 'Works!'
```

### CODE REVIEW

**Comment by haroldiedema** [comment]
Hmm....

I don't like the way the developer has to use `getStatic()` to get to the static-scope.
Since objects can be referenced, why not just call it `static`?

I'd rather do this:
```javascript
var MyClass = Class({
    'public static number foobar': 42,

    construct: function () {
        this.static.foobar = 50;
    }
});

console.log(MyClass.foobar); // This _should_ work and return 42.

new MyClass();

console.log(MyClass.foobar); // This _should_ work and return 50;
```
Since scalar values can't be used as pointers/references, I ran into this problem myself a long time ago. Hence I decided not to implement it. The way it can be achieved is indeed to use some sort of scope (object), but the way people had to use it wasn't something I liked - at all. There's also a performance impact since you have to re-bind an object to the correct scope everytime you instantiate a class, while this _should_ only happen when you declare a class.

I would love to see a correct implementation for this, but I think there are more cons to this than pros :disappointed: 

Right now, using the "const" property type does somewhat what you'd expect it to do.
```javascript
var MyClass = Class({
    'const foobar': 42
});

console.log(MyClass.foobar); // 42.
```
The only problem with this approach is that even though the property is declared as `const`, it can still be modified. I haven't found a way to protect these properties from being modified. This means that effectively, the variable is a static, as long as it's called from the class declaration rather than an instantiated object:

```javascript
var mc = new MyClass();

console.log(MyClass.foobar); // 42
console.log(mc.foobar); // undefined
```

**Comment by cjmanca** [comment]
> I don't like the way the developer has to use getStatic() to get to the static-scope.
> Since objects can be referenced, why not just call it static?

static is a reserved word in javascript, otherwise I would have liked to use that.

Also - they don't *need* to use it if they're using the function method. They can use the argument passed in to access the private static scope (probably name it the same as the class, for consistency). 

Example:

```javascript
var MyClass = JOII.ClassBuilder('MyClass', {}, function (MyClass) { return { 
    'private static number num' : 1,
    'public construct()' : function() {
        MyClass.num = 2; // uses the variable passed to this function
    },
    'public test()' : function() {
        returns MyClass.num; // uses the variable passed to this function
    },
    'public static staticTest(number)' : function(num) {
        returns MyClass.num + num; // uses the variable passed to this function
    }
}});
var mc = new MyClass();
mc.getNum(); // undefined, because private
mc.num; // undefined, because private
mc.test(); // returns 2
MyClass.staticTest(2); // returns 4
```

**Comment by haroldiedema** [comment]
But how is this significantly different than the current `const` implementation?
There isn't that much difference that's worth all this overhead.

I mean, `const` does exactly this (maybe it should be renamed to `static` instead), with the exception that it can't be used from a `this`-scope, but rather directly from the declared class function-prototype itself.

A usecase would be to have "namespaced" classes, for example:

```javascript
var MyFramework = Class({
    'public static Router': Class({
        /* ... */
    }),

    construct: function () {
        this.Router; // undefined because it's static.
        MyFramework.Router; // Class.
    }
});

var router = new MyFramework.Router();
MyFramework.Router = "foobar"; // Since it's static, not a constant, this is allowed. (there isn't really a way to prevent this anyway...)
```

I don't really see any use-cases where one would have to use the "static-scope" over the current `const` implementation. Unless I'm missing something entirely (in which case, please exaplain ;)), I don't see that much difference between the two.

**Comment by cjmanca** [comment]
Because it enforces getter/setter, can take advantage of immutable, and best of all - static overloadable functions.

**Comment by haroldiedema** [comment]
Alright.

Please extend the unit tests a bit, where there are also cases where inheritance is involved with static methods.

Once unit tests are complete, I'll merge it! :+1:

**Comment by cjmanca** [comment]
I removed support for:
this.getStatic()
since it was causing problems with proper static inheritance. The only way to reference static now is through the classname. 
Also - static variables NEED to be referenced through getName()/setName(), even in a private/protected scope now for inheritance reasons (since static variables live in the class they're defined in even when inherited).

**Comment by haroldiedema** [comment]
Looking good 👍 

I'll hold on tagging this in a release until documentation with some code examples are created.

**Pull request merged**
