### PR TITLE
Fixed unit testing in browser

### PR DESCRIPTION
**Pull request by cjmanca**
Now tests properly in browser (with src version), and via npm test (with dist version)

### CODE REVIEW

**Comment by haroldiedema** [comment]
Doesn't work in a browser for me.

```
GET file:///D:/joii/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js net::ERR_FILE_NOT_FOUND
testsuite.html:5 GET file:///D:/joii/node_modules/qunit/node_modules/qunitjs/qunit/qunit.css net::ERR_FILE_NOT_FOUND
DeepCopyTest.js:16 Uncaught ReferenceError: test is not defined(…)(anonymous function) @ DeepCopyTest.js:16
InheritanceTest.js:31 Uncaught ReferenceError: test is not defined(…)(anonymous function) @ InheritanceTest.js:31
PropertyMetaTest.js:10 Uncaught ReferenceError: test is not defined(…)(anonymous function) @ PropertyMetaTest.js:10
TraitTest.js:10 Uncaught ReferenceError: test is not defined(…)
```

**Comment by haroldiedema** [comment]
If you manage to get this working with a modified qunit version, please add the version constraint to package.json and commit that as well.

The tests must work when you do a fresh clone of the repository. Right now, the browser tests don't work.

**Comment by cjmanca** [comment]
Hmm... I just deleted my node_modules directory, and ran "npm install", and all the tests (both npm test and browser tests) work perfectly with these changes...

Could you perhaps try doing the same to make sure there isn't an issue with your node_modules?

**Comment by haroldiedema** [comment]
I did exactly that.

Both on Windows 10 (my desktop pc) and Ubuntu (my vps).

I cloned your fork "as-is" and ran "npm install", followed by "npm test". This works so far.
However, when opening testsuite.html in a browser, after running "npm test", it complains about files not being found, etc.

Since you're using Visual Studio, I assume you also run on Windows.

My VPS still had the old 0.10.x version of Node installed. I've tried it on that as well, but it produces the exact same errors. After upgrading it to the latest version, it's still the same.

**Comment by cjmanca** [comment]
I'm really at a loss now. I just followed those exact same steps you said you did, and again it worked... I just don't understand what's going on.

**Comment by haroldiedema** [comment]
Are you opening testsuite.html from a webserver (http://localhost/) or just running the file itself directly from file exlorer?

**Comment by cjmanca** [comment]
Locally from the file it's self, but I figured it out.

I had NPM version 2.x installed, and it would install all module dependencies in that module's subfolder. In NPM 3.x, they changed it to install the dependencies along side them in the main node_modules folder. Hence the path differences.

I updated my NPM to 3.x, and fixed the issue/committed an update.

**Comment by haroldiedema** [comment]
Aaahh, there we go! :smile:

**Pull request merged**
